chore(website): add Malva and markup_fmt to list
dprint/dprint pull request #876
Opened 2024-07-01 08:31 UTC by g-plane

Close #492 
Close #536 
Close #805

2024-07-04 09:58 UTC, eggplants requested changes
```json
{} // a
```

```jsonc
{} // a
```

2024-07-04 09:58 UTC, eggplants commented on website/src/plugins/malva.md
> +```json
```suggestion
```jsonc
```

2024-07-04 09:58 UTC, eggplants commented on website/src/plugins/markup_fmt.md
> +```json
```suggestion
```jsonc
```

2024-07-04 09:58 UTC, eggplants commented on website/src/plugins/yaml.md
> +```json
```suggestion
```jsonc
```

2024-07-06 21:17 UTC, dsherret approved these changes
Amazing! Thanks @g-plane!

2024-07-06 21:17 UTC, merged

2024-07-06 21:21 UTC, dsherret commented
@g-plane by the way, these can be added to `dprint info` and the playground by updating this file: https://github.com/dprint/plugins/blob/main/info.json